# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='party_number',
            field=models.IntegerField(default=0),
        ),
    ]
