# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_commitment_party_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='check',
            field=models.BooleanField(default=0),
        ),
    ]
