# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_commitment_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Category'),
        ),
    ]
