# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20170212_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='check',
        ),
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
