# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20170212_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Category'),
        ),
    ]
