# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_auto_20170213_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
