# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_category_ctname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
