# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_category_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='detail_commitment',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
