# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_auto_20170215_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='ref',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
