# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_commitment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='commitment',
            field=models.CharField(max_length=200),
        ),
    ]
