# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_commitment_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='imgsrc',
            field=models.CharField(default='../../static/img/1.png', max_length=100),
        ),
    ]
