# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_auto_20170219_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='imgsrc',
        ),
    ]
