# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_auto_20170227_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='idx',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
