# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_auto_20170417_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAdr2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPAdr3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPAdr4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=100)),
            ],
        ),
    ]
